### ISSUE TITLE
fees for ethereum / erc20 tx ?

### ISSUE THREAD

**Issue by kropple** [gochain/web3#153]
firstoff thanks for your great work!

is there any way i can influence the fees gochain-web3 uses when transfering ethereum or erc20 tokens?

i see the "increasegas" parameter,
but i'd like to know how it is handled at all.

is web3 using known good values as fees, or is it looking at the last blocks what others used or is it connecting to something like ethgassstation?

would be nice to have this topic briefly in the documentation.

**Comment by treeder** [comment]
Thanks!

I don't think you can currently set it, it's using the suggested gas directly from the chain nodes: https://github.com/gochain/web3/blob/f7490e0e0810183b7dea82dcbaeb7dd0e1614f88/web3.go#L127

Could be added as a flag to set it explicitly though.

**Comment by treeder** [comment]
There's a `gas-limit` and `gas-price` on some commands now, should add these to transfer and other commands too.
