### ISSUE TITLE
Configurable networks

### ISSUE THREAD

**Issue by blewater** [gochain/web3#168]
I stumbled upon gochain/web3 and it is a nice addition to the existing ecosystem of web3 contract management tools. I have a use case where we are working with the Avalanche EVM chain, but the EVM networks are baked in the source. Would you consider offering ingestion of additional networks and related parameters similar to what [truffle-config.js](https://gist.github.com/cgcardona/03761a1c091ddda0d13f787ec7c88d63)? Can still keep existing defaults and tackle gas-related fees at the same time. If compatible with your objectives, this could come as a PR contribution.
What do you think?

**Comment by treeder** [comment]
Absolutely, happy to support other chains. 

Perhaps a simpler config format though like YAML instead of JavaScript?

**Comment by treeder** [comment]
You can use `WEB3_RPC_URL` to point to any network. Let me know if that doesn't solve this issue.

**Comment by 0ihsan** [comment]
Hi, I am trying to use Avalanche EVM with but can't get it working. What am I doing wrong?

```sh
❯ export WEB3_RPC_URL=https://api.avax.network/ext/bc/C/
❯ web3 balance myaddress
ERROR: Cannot get address balance from the network: 404 Not Found: Not Found
```

**Comment by treeder** [comment]
@0ihsan did you actually put `myaddress` in that command?  You'll want to replace that with your actual address starting with `0x`

**Comment by 0ihsan** [comment]
Yes I did. I didn't want to put my actual address here so I changed it to `myaddress`.

**Comment by treeder** [comment]
the URL is supposed to be: https://api.avax.network/ext/bc/C/rpc (from: https://support.avax.network/en/articles/4626956-how-do-i-set-up-metamask-on-avalanche)

**Comment by 0ihsan** [comment]
That's it! Thank you.
