### ISSUE TITLE
feature: Add gas-price flags to contract call command

### ISSUE THREAD

**Issue by dukemc1** [gochain/web3#176]
Is there a function to define the gasPrice in Gwei - not using the Gas-Price that the chain respone?

**Comment by treeder** [comment]
Many commands support `gas-price` and/or `gas-price-gwei`. Use `--help` for more info on the command.

**Comment by dukemc1** [comment]
OK but in the call contract function Not?

**Comment by dukemc1** [comment]
b:/home/ubuntu/web3_2# ./web3_linux gas-price
No help topic for 'gas-price'
/home/ubuntu/web3_2# ./web3_linux gas-price-gwei
No help topic for 'gas-price-gwei'

**Comment by treeder** [comment]
![image](https://user-images.githubusercontent.com/75826/104849892-13cb4680-58a1-11eb-82a2-82fc382f4d03.png)

Looks like you're right on the `contract call` command. Updating the name of this issue for that.

**Comment by dukemc1** [comment]
Yes but on the other command the output is:

ERROR: flag provided but not defined: -gas-price

**Comment by dukemc1** [comment]
Add in main.go at line 463

cli.StringFlag{
                                        Name:  "gas-price",
                                        Usage: "Gas price to use, if left blank, will use suggested gas price.",
                                },
                                cli.StringFlag{
                                        Name:  "gas-price-gwei",
                                        Usage: "Gas price to use in GWEI, if left blank, will use suggested gas price.",

then the gas-price could get set in contracts ;)

**Comment by treeder** [comment]
Pull request? 🙂

**Comment by r-gochain** [comment]
https://github.com/gochain/web3/pull/177

**Comment by treeder** [comment]
Closes via #177
