### ISSUE TITLE
Impossible to connect to ropsten network

### ISSUE THREAD

**Issue by jeremyfritzen** [gochain/web3#178]
Hi,

I set the WEB3_NETWORK and WEB3_PRIVATE_KEY environment variables and can access the main Ethereum network without issue.
But when I change WEB3_NETWORK environment variable with "ropsten", it doesn't work anymore. Here is what I get when I try the command `web3 balance`:

```
ERROR: Cannot get address balance from the network: 502 Bad Gateway <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

Did anyone experience the same issue?
How can I use this tool with ropsten?

Thanks for your help!

**Comment by treeder** [comment]
Looks like linkpool.io shut down their ropsten rpc service, so we'll have to find an alternative.

**Comment by treeder** [comment]
Alternatively, we could allow a URL for the WEB3_NETWORK and then let people use whatever RPC gateway they want, such as their own infura URL. @jmank88 @r-gochain thoughts?

**Comment by jeremyfritzen** [comment]
Thanks!
I didn't notice that we were already able to specify a custom address.
I know this is not really on this github team but, can someone give me a URL? I only used a testnet one or 2 times and don't know exactly where I can find specific RPC testnet address.
Thanks a lot!

**Comment by treeder** [comment]
Login to infura.io , under settings you'll see ENDPOINTS, choose Ropsten and it'll give you URLs.

**Comment by jeremyfritzen** [comment]
Thanks!
