### ISSUE TITLE
New feature: set the nonce for a new transaction

### ISSUE THREAD

**Issue by jeremyfritzen** [gochain/web3#179]
I think this is not possible at that time. If it is, so not hesitate to close this thread.

I would like to be able to set a custom nonce for a new transaction. This way, we would be able to do some advanced operations, such as unblocking a blocked transaction because of too low gas price.

Thanks a lot!

**Comment by treeder** [comment]
You might want to look at `replace` and `increasegas` which both replace transactions.

**Comment by jeremyfritzen** [comment]
Thanks?
What do you mean by those ones? Are they other programs you recommend? Or a specific command of this web3 software?

**Comment by treeder** [comment]
web3 commands. try `web3 replace --help`

**Comment by jeremyfritzen** [comment]
feature already exists
