### ISSUE TITLE
Error when trying to get the balance "Too many requests" 

### ISSUE THREAD

**Issue by jeremyfritzen** [gochain/web3#180]
Hi,

I executed a lot of request since several hours and finally got the following answer when trying to retrieve the balance (`web3 --network=ethereum balance <public_address>`):

`ERROR: Cannot get address balance from the network: 429 Too Many Requests {"jsonrpc":"2.0","id":1,"error":{"code":-32005,"message":"daily request count exceeded, request rate limited","data":{"rate":{"allowed_rps":1,"backoff_seconds":0,"current_rps":2.2},"see":"https://infura.io/dashboard"}}}`

I understand that I sent too many requests but I don't understand why this message asks me to see "infura.io/dashboard" since I am not using a testnet but the real ethereum network.

Why do I have this limitation since I'm not using the testnet?

Thanks

**Comment by jmank88** [comment]
Hi @jeremyfritzen,

The `--network=ethereum` flag currently uses a public Infura RPC URL (https://github.com/gochain/web3/blob/master/networks.go#L30), and so this is Infura's error and limit that you are seeing, not our own.

**Comment by treeder** [comment]
You should probably use `WEB3_RPC_URL/--rpc-url` and pass in your own infura URL with your own key. 

Wonder if we should just only allow that for Ethereum since there doesn't seem to be any free rpc hosts for Ethereum anymore?

**Comment by jeremyfritzen** [comment]
Ok I got it thanks!
Infura is a kind of API gateway to send requesy to the Ethereum network.
I think you can things like that. Using your default infura account is a good way to start but then users should use their own account.

**Comment by treeder** [comment]
I'm going to keep this open, I think we should change our docs to explain this since everyone will run into this once the limit is reached on the account we're using.

**Comment by jeremyfritzen** [comment]
Ok!
Actually, it wasn't that difficult. I found the solution before your answers ^^
But you are right, it would be better to update the documentation :)

Thanks!

**Comment by treeder** [comment]
I updated the README to let people know to use `WEB3_RPC_URL` for ethereum.
