### ISSUE TITLE
What about EIP1559 on Ethereum?

### ISSUE THREAD

**Issue by jeremyfritzen** [gochain/web3#184]
I'm just wondering what will be the impacts of the implementation of EIP1559 (Ethereum evolution) on this tool?
Will it still be possible to make transactions on Ethereum network with gochain web3 tool?
If the EIP1559 requires some new development on gochain web3 tool, is it planned to be implemented before July 2021 (target date of EIP1559 implementation on Ethereum mainnet)?

Thanks!

**Comment by treeder** [comment]
We'll definitely implement whatever changes are required so it continues to work, yes.

**Comment by jeremyfritzen** [comment]
Ok great, thank you.
I don't how difficult or easy it will be. Do you have any idea of the timeline?

**Comment by treeder** [comment]
I don't know either, but we probably won't look at it until it's closer to reality. Or someone can do a pull request and do it themselves.
