### ISSUE TITLE
Compilation fails with solc 0.8+

### ISSUE THREAD

**Issue by fabiangandila** [gochain/web3#199]
Hello,
I have updated my environment as follows:
- solc, the solidity compiler commandline interface
Version: 0.8.4+commit.c7e474f2.Linux.g++
- go version go1.16.3 linux/amd64
- web3 version 0.2.62
I wanted to test the build & deployment of a generic contract using web3 cli but I get the following error after the flatten *.sol is generated:

![image](https://user-images.githubusercontent.com/28136530/116130053-73709380-a6d3-11eb-9295-eabee31154cc.png)

![image](https://user-images.githubusercontent.com/28136530/116130180-98fd9d00-a6d3-11eb-83c9-5fd290eb3770.png)

**Comment by treeder** [comment]
Checking it out now...

**Comment by treeder** [comment]
re https://github.com/ethereum/go-ethereum/issues/22041

**Comment by treeder** [comment]
Give it a try now.
