### ISSUE TITLE
cannot set both rpcURL and network

### ISSUE THREAD

**Issue by sinanouri** [gochain/web3#203]
i installed web3 and as mentioned in documentation added export data

```
export WEB3_NETWORK=ethereum

export WEB3_PRIVATE_KEY=0x123456789

export WEB3_RPC_URL=https://mainnet.infura.io/v3/123456789
```
but when running web3 balance it tells me 

ERROR: Cannot set both rpcURL "https://mainnet.infura.io/v3/123456789" and network {"" "" "" ""}

**Comment by treeder** [comment]
unset WEB3_NETWORK if you're using RPC URL.

**Comment by sinanouri** [comment]
İ sid and it is working but balance shows GO instead of ETH

**Comment by treeder** [comment]
What balance?

**Comment by sinanouri** [comment]
when i type  web3 balance it shows:
0.595850329309322292 GO
while this is my ETH balance
