### ISSUE TITLE
ERROR: Error calling contract: invalid private key: invalid length, need 256 bits

### ISSUE THREAD

**Issue by aug2uag** [gochain/web3#223]
getting this in v0.2.69 but not v0.2.66 with the following:

```
web3 contract call --address $CONTRACT \
--gas-limit 800000 --abi K.abi \
--function mintWithTokenURI $ADDR $TOKENID $URI
```

**Comment by NiSHoW** [comment]
#219 #220

**Comment by treeder** [comment]
Please upgrade to v0.2.70 and try again.

**Comment by aug2uag** [comment]
I can confirm this operation is successful now and the issue may be closed.
Thanks for your quick response!
