### ISSUE TITLE
Please support ARM devices again

### ISSUE THREAD

**Issue by bitcoinmeetups** [gochain/web3#238]
Hello,

I'm MB. A very nice and polite guy.

Please support ARM devices again. In the beginning web3 worked with ARM. Now it doesn't. Please support it again, lots of people use ARM CPU's these days.

This error message is what I get:

Error: you are not using a 64bit platform.
Web3 CLI currently only supports 64bit platforms.

I mean you obviously can support ARM because web3 worked on my device before. So why stop? Please just reverse this decision so I can start coding with web3 again, it's such a fun package.

**Comment by treeder** [comment]
I actually don't recall why it's limited to 64 bit. @r-gochain any ideas?

**Comment by treeder** [comment]
https://github.com/gochain/web3/blob/e956a76abb31b83bfb595472cd1c9cbe4be2c8c3/install.sh#L20

**Comment by r-gochain** [comment]
@treeder I believe it was just a copy paste and one more reason that we didn't test on any other platform except x64.
@bitcoinmeetups what is your CPU? could you post an output of `uname -m` command here?

**Comment by r-gochain** [comment]
@treeder I suppose the problem is that we don't have a binary built for ARM architecture

![image](https://user-images.githubusercontent.com/40002763/147460012-26cc8279-1b18-4860-9f92-ce656f7b8cac.png)

**Comment by r-gochain** [comment]
@treeder ARM64 support (I'm not sure that there are arm32 devices that could run linux/mac still exist and popular) - https://github.com/gochain/web3/pull/239

**Comment by bitcoinmeetups** [comment]
armv8l-linux-gnu AArch32 Hard

Go-web3 used to work on this device before. Please support it again. I want to use web3 a lot and I have many ideas.

-------- Original Message --------

**Comment by r-gochain** [comment]
@bitcoinmeetups it would work, we just don't build it for this arch (and have never built before).
The easiest way for you would be just to build it using the following command
```GOOS=linux GOARCH="arm" go build  -o web3_linux_arm64 ./cmd/web3``` (inside this repo after you clone it)

**Comment by bitcoinmeetups** [comment]
I will try and update if it worked to build it.
