### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference                 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x783398]                                                                                                         goroutine 1 [running]:                                                                  github.com/gochain/web3.ParseLogs({{{0x0, 0x0}, {0x0, 0x0}, 0x0, {0xc0003c5230, 0xa}, 0x0, 0x0, {0x11626a0, ...}, ...}, ...}, ...)

### ISSUE THREAD

**Issue by bitcoinmeetups** [gochain/web3#252]
Hello,

I'm BM. A very nice and polite guy. Recently I was trying to mint some tokens using this command:

web3 contract call --wait --abi CAT.abi --gas-limit 2000000 --function mint 0xabcmyaddress

I get the same type of error message both on my local computer (RPi4) as well as on my server:

panic: runtime error: invalid memory address or nil pointer dereference                 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x783398]                                                                                                         goroutine 1 [running]:                                                                  github.com/gochain/web3.ParseLogs({{{0x0, 0x0}, {0x0, 0x0}, 0x0, {0xc0003c5230, 0xa}, 0x0, 0x0, {0x11626a0, ...}, ...}, ...}, ...)

Anyone knows how to solve this issue?

**Comment by r-gochain** [comment]
Let me check that

**Comment by r-gochain** [comment]
@bitcoinmeetups could you please share the ABI and the contract address?

**Comment by r-gochain** [comment]
@bitcoinmeetups even transaction hash is enough
