### ISSUE TITLE
Image does not show up in Metamask

### ISSUE THREAD

**Issue by bitcoinmeetups** [gochain/web3#255]
Hello,

I'm BM. A very nice and polite guy.

I still cannot build on my Rpi4 but I can build and mint on a server. 

However the image doesn't show up. 

My json file looks like this:

https://ipfs.io/ipfs/bafkreicgarp442gkylayy6c3344jfii7caayk6d2d37e2prsrk2wfx5ope?filename=nft.json

In fact I used the URL above as the third field here:

ERC721PresetMinterPauserAutoId("Hello", "HELLO", "https://ipfs.io/ipfs/bafkreihgaxvckivgaliyvgbrnendokhm3h3n2pf2rns4u7rfqwrz7k4yyi?filename=nft.json")

I know, maybe I cut a few corners. I tested with a similar URI before though and that worked, the picture did show up in Metamask. But that was some example I found in issue 196. Now when I wanted to use my own picture the above line did not work. I wonder why. The picture does not have any special file or format requirements, right? I used a small JPG, maybe 200 x 200 pixels.

The test image is here: https://ipfs.io/ipfs/bafkreic7bf65qfmziremfhzlryetum5dqjfbia2gxa5mhvhmk6mqht3fma?filename=bitcoin3.jpg

Any idea why it didn't show up in MetaMask? Because I've already tested the line above before and it works for someone else's picture but not for mine.

**Comment by treeder** [comment]
Sounds like a question for Metamask?  Or reading the Metamask docs, not sure what requirements they have.
